---
- hosts: all
  become: true
  tasks:
    - name: 'Install httpd package'
      yum:
        name: vsftpd
        state: installed
    - name: 'Start service'
      service:
        name: vsftpd
        state: started
